GET http://localhost:8080/items/1234

###

POST http://localhost:8080/echo
Content-Type: application/json

{
	"geust": "Bread",
	"quantity": 1,
	"other_field": "some value"
}

###

PATCH http://localhost:8080/items/1234


{
	"name": {
		"first_name": "Kevin",
		"last_name": "Cunningham"
	}
}